name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - dev  # 监听 main 分支的推送事件（你也可以设置其他分支）

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.112.2'  # 选择你需要的 Hugo 版本

      - name: Build site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GithubBotToken }}
          publish_dir: ./public
          publish_branch: gh-pages  # 如果你使用的是 gh-pages 分支
