name: Deploy Docs

on:
  push:
    branches:
      - dev 

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.123.7'
          extended: true
        
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          make install
          make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBBOTTOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
